import { useEffect, useState } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowUpRight, Wheat, Menu, X, FileText, Package, Flame, Sprout, Leaf, Zap, CircleDot } from 'lucide-react';
import { Button } from '@/components/ui/button';
export function Brand() {return <Link to="/" className="brand"><Wheat className="brand-mark" size={25}/><span>stubble <span className="text-primary">→</span> value<span className="text-primary">.</span></span></Link>}
export function Header() {const [open,setOpen]=useState(false);const links=<><Link to="/" onClick={()=>setOpen(false)}>The idea</Link><Link to="/options" onClick={()=>setOpen(false)}>Explore possibilities</Link><Link to="/buyers" onClick={()=>setOpen(false)}>Find buyers</Link><Link to="/impact" onClick={()=>setOpen(false)}>Your impact</Link></>;return <header className="site-header"><Brand/><nav className="nav-links">{links}</nav><Button asChild className="desktop-cta"><Link to="/calculator">Calculate my stubble <ArrowUpRight/></Link></Button><Button variant="ghost" size="icon" className="mobile-nav" aria-label={open?'Close menu':'Open menu'} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button>{open&&<nav className="menu-panel">{links}<Button asChild><Link to="/calculator" onClick={()=>setOpen(false)}>Calculate my stubble <ArrowUpRight/></Link></Button></nav>}</header>}
export function Footer() {return <footer className="site-footer"><Brand/><span>More value for farmers. A better future for everyone.</span><span>Built for a circular tomorrow · Demo experience</span></footer>}
export function OptionIcon({name,...props}:{name:string; size?:number;className?:string}) {const Icon=({paper:FileText,box:Package,flame:Flame,sprout:Sprout,leaf:Leaf,mushroom:CircleDot,energy:Zap,wheat:Wheat} as Record<string,typeof Wheat>)[name]??Leaf;return <Icon {...props}/>}
export function Counter({value,decimals=1}:{value:number;decimals?:number}) {const [shown,setShown]=useState(value);useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches){setShown(value);return;}let frame=0;const start=performance.now();const tick=(now:number)=>{const p=Math.min((now-start)/650,1);setShown(value*(1-Math.pow(1-p,3)));if(p<1) frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[value]);return <>{shown.toLocaleString('en-IN',{minimumFractionDigits:decimals,maximumFractionDigits:decimals})}</>}
export const meta = (title:string,description:string)=>({meta:[{title:`${title} — Stubble → Value`},{name:'description',content:description},{property:'og:title',content:`${title} — Stubble → Value`},{property:'og:description',content:description},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]});
